baseURL = "https://www.rohrbachscience.com"
languageCode = "en-us"
title = "Rohrbach Science"
theme = "rohrbachsci"
SectionPagesMenu = "main"
paginate = 5

[params]
  twitter = "https://www.twitter.com/rohrbachsci"
  youtube = "https://www.youtube.com/channel/UCE3yLLQT9geEgeYPgyWwZLA"
  github = "https://github.com/zjrohrbach"
  linkedin = "https://www.linkedin.com/in/zacharyrohrbach/"
  favicon = "/favicon-32x32.png"
  website-defined-css = "/website-defined.css"

########################################################################
## the following has to be here for live-pagination on rohrbachsci    ##
##                         theme to work                              ##
########################################################################


[outputFormats]
  [outputFormats.HTML_Snippet]
    mediaType = 'text/html'
    isHTML = true
    baseName = 'snip'

[outputs]
  home = ['HTML', 'HTML_Snippet']
