baseURL = "https://www.rohrbachscience.com"
languageCode = "en-us"
title = "Rohrbach Science"
theme = "rohrbachsci"
SectionPagesMenu = "main"
paginate = 5

[outputFormats]
  [outputFormats.HTML-Snippet]
    mediaType = 'text/html'
    isHTML = true
    path = 'snippets'

[outputs]
  home = ['HTML', 'JSON', 'HTML-Snippet']

[params]
  twitter = "https://www.twitter.com/rohrbachsci"
  youtube = "https://www.youtube.com/channel/UCE3yLLQT9geEgeYPgyWwZLA"
  github = "https://github.com/zjrohrbach"
  linkedin = "https://www.linkedin.com/in/zacharyrohrbach/"
  favicon = "/favicon-32x32.png"
  website-defined-css = "/website-defined.css"